# Generated by Django 4.0.6 on 2022-07-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_number',
            field=models.CharField(max_length=50),
        ),
    ]
