# Generated by Django 4.0.6 on 2022-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_alter_truck_truck_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='vin_number',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
