# Generated by Django 4.0.6 on 2022-07-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_load_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='resolved',
        ),
    ]
