# Generated by Django 4.0.6 on 2022-07-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('medical_card_number', models.CharField(max_length=50)),
                ('medical_card_expiry_date', models.DateField(blank=True)),
                ('truck_number', models.IntegerField()),
                ('driver_license_numbers', models.IntegerField()),
                ('driver_license_expiry_date', models.DateField(blank=True)),
                ('certification', models.CharField(choices=[('hazard', 'Hazard'), ('tanker_endorsement', 'Tanker Endorsement'), ('both', 'Both Hazard and Tanker Endorsement'), ('neither', 'Neither')], max_length=50)),
            ],
        ),
    ]
