# Generated by Django 4.0.6 on 2022-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driver_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='citizenship',
            field=models.CharField(choices=[('citizen', 'C (citizen)'), ('non_citizen', 'PR (permanent residence)'), ('work_permit', 'WP (work permit)')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='certification',
            field=models.CharField(choices=[('hazard', 'Hazard'), ('tanker_endorsement', 'Tanker Endorsement'), ('both', 'Both Hazard and Tanker Endorsement'), ('neither', 'Neither')], max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_license_numbers',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_card_expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='medical_card_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck_number',
            field=models.CharField(max_length=50),
        ),
    ]
