# Generated by Django 4.0.6 on 2022-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_driver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('citizen', 'C (citizen)'), ('non_citizen', 'PR (permanent residence)'), ('work_permit', 'WP (work permit)')], default=None, max_length=50),
        ),
    ]
