# Generated by Django 4.0.6 on 2022-07-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_alter_driver_citizenship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='citizenship',
            field=models.CharField(choices=[('citizen', 'C (citizen)'), ('non_citizen', 'PR (permanent residence)'), ('work_permit', 'WP (work permit)')], max_length=50, null=True),
        ),
    ]
