# Generated by Django 4.0.6 on 2022-07-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailor_number', models.CharField(max_length=50)),
                ('driver_assigned_to', models.CharField(max_length=50)),
                ('registration_current_date', models.DateField(blank=True)),
                ('registration_expiry_date', models.DateField(blank=True)),
                ('inspection_current_date', models.DateField(blank=True)),
                ('inspection_expiry_date', models.DateField(blank=True)),
            ],
        ),
    ]
