# Generated by Django 4.0.6 on 2022-07-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailor',
            name='manufacturer_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='trailor',
            name='vented',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='trailor',
            name='vin_number',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
