# Generated by Django 4.0.6 on 2022-07-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailors', '0002_trailor_manufacturer_date_trailor_vented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailor',
            name='vented',
            field=models.BooleanField(default=False),
        ),
    ]
